
package com.oracle.xmlns.telecomservicesplatform.telecombuyflow.servicebuyflow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.oracle.xmlns.soalab.servicebuyflow.servicebuyflow.ObjectFactory;
import com.oracle.xmlns.soalab.servicebuyflow.servicebuyflow.Process;
import com.oracle.xmlns.soalab.servicebuyflow.servicebuyflow.ProcessResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebService(name = "execute_ptt",
            targetNamespace = "http://xmlns.oracle.com/TelecomServicesPlatform/TelecomBuyFlow/ServiceBuyFlow")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ExecutePtt {


    /**
     *
     * @param partProcessRequest
     * @return
     *     returns com.oracle.xmlns.soalab.servicebuyflow.servicebuyflow.ProcessResponse
     */
    @WebMethod(action = "execute")
    @WebResult(name = "processResponse",
               targetNamespace = "http://xmlns.oracle.com/SOALab/ServiceBuyFlow/ServiceBuyFlow",
               partName = "partProcessResponse")
    public ProcessResponse execute(@WebParam(name = "process",
                                             targetNamespace =
                                             "http://xmlns.oracle.com/SOALab/ServiceBuyFlow/ServiceBuyFlow",
                                             partName = "partProcessRequest") Process partProcessRequest);

}
