
package com.oracle.xmlns.telecomservicesplatform.telecombuyflow.servicebuyflow;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * OSB Service
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10-b140319.1121
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "execute_bindQSService",
                  targetNamespace = "http://xmlns.oracle.com/TelecomServicesPlatform/TelecomBuyFlow/ServiceBuyFlow",
                  wsdlLocation =
                  "https://fmw01-wls-1:7104/TelecomBuyFlow/ServiceBuyFlowProxy?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FTelecomServicesPlatform%2FTelecomBuyFlow%2FServiceBuyFlow%7Dexecute_bindQSService")
public class ExecuteBindQSService extends Service {

    private final static URL EXECUTEBINDQSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXECUTEBINDQSSERVICE_EXCEPTION;
    private final static QName EXECUTEBINDQSSERVICE_QNAME =
        new QName("http://xmlns.oracle.com/TelecomServicesPlatform/TelecomBuyFlow/ServiceBuyFlow",
                  "execute_bindQSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://fmw01-wls-1:7104/TelecomBuyFlow/ServiceBuyFlowProxy?wsdl#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FTelecomServicesPlatform%2FTelecomBuyFlow%2FServiceBuyFlow%7Dexecute_bindQSService");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXECUTEBINDQSSERVICE_WSDL_LOCATION = url;
        EXECUTEBINDQSSERVICE_EXCEPTION = e;
    }

    public ExecuteBindQSService() {
        super(__getWsdlLocation(), EXECUTEBINDQSSERVICE_QNAME);
    }

    public ExecuteBindQSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXECUTEBINDQSSERVICE_QNAME, features);
    }

    public ExecuteBindQSService(URL wsdlLocation) {
        super(wsdlLocation, EXECUTEBINDQSSERVICE_QNAME);
    }

    public ExecuteBindQSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXECUTEBINDQSSERVICE_QNAME, features);
    }

    public ExecuteBindQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecuteBindQSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_bindQSPort")
    public ExecutePtt getExecuteBindQSPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/TelecomServicesPlatform/TelecomBuyFlow/ServiceBuyFlow",
                                       "execute_bindQSPort"), ExecutePtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_bindQSPort")
    public ExecutePtt getExecuteBindQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/TelecomServicesPlatform/TelecomBuyFlow/ServiceBuyFlow",
                                       "execute_bindQSPort"), ExecutePtt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXECUTEBINDQSSERVICE_EXCEPTION != null) {
            throw EXECUTEBINDQSSERVICE_EXCEPTION;
        }
        return EXECUTEBINDQSSERVICE_WSDL_LOCATION;
    }

}
