package com.oracle.xmlns.telecomservicesplatform.telecombuyflow.servicebuyflow;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.3.0.0.1008
public class execute_bindQSPortClient {
    public static void main(String[] args) {
        ExecuteBindQSService executeBindQSService = new ExecuteBindQSService();
        ExecutePtt executePtt = executeBindQSService.getExecuteBindQSPort();
        // Add your code to call the desired methods.


    }
}
